export const LANDING = '/';
export const INBOX = '/inbox';
export const SYLLABUS = '/syllabus';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const PASSWORD_FORGET = '/pw-forget';
export const ACCOUNT = '/account';
// export const ADMIN = '/admin';